pool:
  vmImage: ubuntu-latest

steps:   
# - task: CopyFilesOverSSH@0
#   inputs:
#     sshEndpoint: $(sshServiceConnectionName)
#     sourceFolder: 'scripts'
#     contents: '**'
#     readyTimeout: '20000'

# - script: |
#     cd ~/.ssh
#     ls
# - task: SSH@0
#   inputs:
#     sshEndpoint: 'AWS EC2 VM - Vingtaine'
#     runOptions: 'script'
#     scriptPath: 'scripts/setup-env.sh'
#     failOnStdErr: false
#     readyTimeout: '20000'

- task: DownloadSecureFile@1
  name: 'azurePipelinesPk'
  inputs:
    secureFile: 'azure-pipelines'

- script: |
    chmod 400 $(azurePipelinesPk.secureFilePath)
    ssh -i $(azurePipelinesPk.secureFilePath) ubuntu@ec2-3-16-216-221.us-east-2.compute.amazonaws.com
    pwd
    ls