trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'pleyce.app'
    runOptions: 'commands'
    commands: |
      if [-d "/Workspace" ]; then
        echo "Directory already exists";
      else
        `sudo mkdir -m 777 /Workspace`;
      fi
    readyTimeout: '20000'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'pleyce.app'
    sourceFolder: 'scripts'
    contents: '**'
    targetFolder: '/Workspace'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'pleyce.app'
    runOptions: 'script'
    scriptPath: 'scripts/setup-env.sh'
    readyTimeout: '20000'