pool:
  vmImage: ubuntu-latest

steps:   
# - task: CopyFilesOverSSH@0
#   inputs:
#     sshEndpoint: $(sshServiceConnectionName)
#     sourceFolder: 'scripts'
#     contents: '**'
#     readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'AWS EC2 VM - Vingtaine'
    runOptions: 'script'
    scriptPath: 'scripts/setup-env.sh'
    failOnStdErr: false
    readyTimeout: '20000'