# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'pleyce.app'
    runOptions: 'commands'
    commands: |
      sudo mkdir /Workspace
      sudo chmod 777 /Workspace
    readyTimeout: '20000'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'pleyce.app'
    sourceFolder: 'scripts'
    contents: '**'
    targetFolder: '/Workspace'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'pleyce.app'
    runOptions: 'script'
    scriptPath: 'scripts/setup-env.sh'
    readyTimeout: '20000'